# Generated by Django 5.0.6 on 2024-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
