# Generated by Django 5.0.6 on 2024-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estadp', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Terminado')], max_length=1)),
            ],
        ),
    ]
